spring:
    application:
        name: limstar-config-server

    cloud:
        config:
            server:
                git:
                    uri: https://github.com/pjlimstars/your-config-repo.git
                    default-label: main
                    clone-on-start: true
                    search-paths: config